import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import postgres from 'postgres';
import { startTestDatabase } from './harness';
import type { TestDb } from './harness';
import { makeDocx, makePdf } from './fixtures';

/**
 * Knowledge Layer — extraction, chunking, the queue, and isolation.
 *
 * Extraction is tested against real PDF and DOCX files generated byte by byte,
 * not stubs, because an extractor that works on a fake is worth nothing.
 */

let db: TestDb;
let appSql: postgres.Sql;
let adminSql: postgres.Sql;
let storageDir: string;

type Scope = { companyId: string; userId: string; role: 'owner' };
let mm: Scope;
let nh: Scope;

let drive: typeof import('../src/server/drive/service');
let processing: typeof import('../src/server/drive/processing');
let chunker: typeof import('../src/server/drive/extraction/chunk');
let extraction: typeof import('../src/server/drive/extraction');

const NL = String.fromCharCode(10);
const PASSWORD = 'cip-demo-password';

/**
 * Empties the queue so a test that cares which file it claims actually gets
 * that file, rather than something an earlier test left behind.
 */
async function parkPendingWork(): Promise<void> {
  await adminSql`
    update drive_files
       set processing_status = 'processed', next_attempt_at = null, processing_started_at = null
     where processing_status in ('pending', 'processing')
       and file_type = any(array['pdf', 'docx', 'txt', 'csv'])
  `;
}

/** Claims and processes until the queue is empty, as the worker does. */
async function drainQueue(): Promise<number> {
  let done = 0;
  for (;;) {
    const file = await processing.claimNextFile();
    if (!file) break;
    await processing.processClaimedFile(file);
    done += 1;
  }
  return done;
}

const upload = (scope: Scope, filename: string, body: Buffer, mimeType: string) =>
  drive.uploadFile(scope, { folderId: null, filename, mimeType, body });

before(async () => {
  db = await startTestDatabase();
  storageDir = mkdtempSync(join(tmpdir(), 'cip-knowledge-'));

  process.env.DATABASE_ADMIN_URL = db.adminUrl;
  process.env.CIP_APP_DB_PASSWORD = db.appPassword;
  process.env.SESSION_SECRET = 'test-session-secret-at-least-32-characters-long';
  process.env.CIP_SEED_PASSWORD = PASSWORD;
  process.env.CIP_STORAGE_DIR = storageDir;
  process.env.CIP_FORCE_LOCAL_STORAGE = 'true';

  const { migrate } = await import('../src/server/migrate');
  await migrate(() => {});
  const { seed } = await import('../src/server/seed');
  await seed(() => {});

  process.env.DATABASE_URL = db.appUrl;
  drive = await import('../src/server/drive/service');
  processing = await import('../src/server/drive/processing');
  chunker = await import('../src/server/drive/extraction/chunk');
  extraction = await import('../src/server/drive/extraction');

  adminSql = postgres(db.adminUrl, { onnotice: () => {} });
  appSql = postgres(db.appUrl, { onnotice: () => {} });

  const rows = await adminSql<{ slug: string; company_id: string; user_id: string }[]>`
    select c.slug, c.id as company_id, u.id as user_id
      from companies c
      join memberships m on m.company_id = c.id
      join users u on u.id = m.user_id
     where u.email in ('sneha@magicmoments.test', 'rahul@narayanahealth.test')
  `;
  const a = rows.find((r) => r.slug === 'magic-moments')!;
  const b = rows.find((r) => r.slug === 'narayana-health')!;
  mm = { companyId: a.company_id, userId: a.user_id, role: 'owner' };
  nh = { companyId: b.company_id, userId: b.user_id, role: 'owner' };
}, { timeout: 180_000 });

after(async () => {
  await appSql?.end();
  await adminSql?.end();
  await db?.stop();
  try {
    rmSync(storageDir, { recursive: true, force: true });
  } catch {
    /* temp dir */
  }
});

describe('extraction reads real files', () => {
  it('reads a PDF', async () => {
    const file = await upload(mm, 'brand-guidelines.pdf',
      makePdf(['Magic Moments brand guidelines', 'Warm, witty and a little cinematic.']), 'application/pdf');

    await drainQueue();

    const result = await processing.getExtraction(mm, file.id);
    assert.ok(result, 'no extraction was recorded');
    assert.match(result.content, /Magic Moments brand guidelines/);
    assert.match(result.content, /cinematic/);
    assert.equal(result.extractor, 'pdfjs');
    assert.equal(result.pageCount, 1);
    assert.ok(result.chunkCount > 0);
  });

  it('reads a DOCX', async () => {
    const file = await upload(mm, 'tone.docx',
      makeDocx(['Tone of voice', 'Talk about the occasion, never the alcohol.']),
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document');

    await drainQueue();

    const result = await processing.getExtraction(mm, file.id);
    assert.ok(result);
    assert.match(result.content, /Talk about the occasion/);
    assert.equal(result.extractor, 'mammoth');
  });

  it('reads a TXT, including UTF-16', async () => {
    const plain = await upload(mm, 'notes.txt', Buffer.from('Plain notes about the campaign.'), 'text/plain');
    const utf16 = await upload(mm, 'notes-utf16.txt',
      Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from('Wide notes here.', 'utf16le')]), 'text/plain');

    await drainQueue();

    assert.match((await processing.getExtraction(mm, plain.id))!.content, /Plain notes/);
    const wide = (await processing.getExtraction(mm, utf16.id))!;
    assert.match(wide.content, /Wide notes here/);
    assert.ok(wide.warnings.includes('decoded-as-utf16le'));
  });

  it('reads a CSV into text that keeps its column names', async () => {
    const csv = ['Month,Assets,Campaigns', 'April,12,3', 'May,18,4'].join(NL);
    const file = await upload(mm, 'report.csv', Buffer.from(csv), 'text/csv');

    await drainQueue();

    const result = await processing.getExtraction(mm, file.id);
    assert.ok(result);
    assert.match(result.content, /Columns: Month, Assets, Campaigns/);
    // The header travels with each row, so a chunk still makes sense alone.
    assert.match(result.content, /Month: April; Assets: 12; Campaigns: 3/);
  });

  it('leaves file types it does not read alone', async () => {
    const png = await upload(mm, 'logo.png',
      Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'),
      'image/png');

    await drainQueue();

    const [row] = await adminSql<{ processing_status: string; processing_attempts: number }[]>`
      select processing_status, processing_attempts from drive_files where id = ${png.id}
    `;
    assert.equal(row!.processing_status, 'pending', 'an image should not have been claimed');
    assert.equal(row!.processing_attempts, 0);
    assert.equal(await processing.getExtraction(mm, png.id), null);
  });
});

describe('extraction handles files it cannot read', () => {
  it('fails a corrupt PDF, records why, and retries', async () => {
    const file = await upload(mm, 'broken.pdf', Buffer.from('%PDF-1.4 this is not really a pdf'), 'application/pdf');

    const claimed = await processing.claimNextFile();
    assert.equal(claimed?.id, file.id);
    const outcome = await processing.processClaimedFile(claimed!);

    assert.equal(outcome.status, 'failed');
    assert.equal(outcome.status === 'failed' && outcome.willRetry, true);

    const [row] = await adminSql<
      { processing_status: string; processing_attempts: number; processing_error: string | null; next_attempt_at: Date | null }[]
    >`select processing_status, processing_attempts, processing_error, next_attempt_at
        from drive_files where id = ${file.id}`;
    assert.equal(row!.processing_status, 'pending', 'should be queued for another try');
    assert.equal(row!.processing_attempts, 1);
    assert.ok(row!.processing_error, 'no reason was recorded');
    assert.ok(row!.next_attempt_at, 'no backoff was set');

    // Backoff means it is not immediately claimable again.
    assert.equal(await processing.claimNextFile(), null);
  });

  it('gives up after the maximum attempts', async () => {
    const file = await upload(mm, 'hopeless.pdf', Buffer.from('not a pdf at all'), 'application/pdf');

    for (let attempt = 1; attempt <= processing.MAX_ATTEMPTS; attempt += 1) {
      // Clear the backoff so the next attempt is claimable straight away.
      await adminSql`update drive_files set next_attempt_at = null where id = ${file.id}`;
      const claimed = await processing.claimNextFile();
      assert.ok(claimed, `expected to claim on attempt ${attempt}`);
      await processing.processClaimedFile(claimed);
    }

    const [row] = await adminSql<{ processing_status: string; processing_attempts: number }[]>`
      select processing_status, processing_attempts from drive_files where id = ${file.id}
    `;
    assert.equal(row!.processing_status, 'failed');
    assert.equal(row!.processing_attempts, processing.MAX_ATTEMPTS);

    await adminSql`update drive_files set next_attempt_at = null where id = ${file.id}`;
    assert.equal(await processing.claimNextFile(), null, 'a failed file must not be claimed again');
  });

  it('treats a PDF with no text layer as read, with a warning', async () => {
    // A page with no text operators is what a scan looks like to pdf.js.
    const file = await upload(mm, 'scanned.pdf', makePdf([]), 'application/pdf');
    await drainQueue();

    const result = await processing.getExtraction(mm, file.id);
    assert.ok(result, 'a scan should still produce an extraction');
    assert.ok(result.warnings.includes('no-text-layer'));
    assert.equal(result.chunkCount, 0);

    const [row] = await adminSql<{ processing_status: string }[]>`
      select processing_status from drive_files where id = ${file.id}
    `;
    assert.equal(row!.processing_status, 'processed');
  });

  it('re-processing replaces the extraction rather than piling up', async () => {
    const file = await upload(mm, 'idempotent.txt', Buffer.from('One paragraph of stable text.'), 'text/plain');
    await drainQueue();

    const first = await processing.getExtraction(mm, file.id);
    await processing.requestReprocess(mm, file.id);
    await drainQueue();
    const second = await processing.getExtraction(mm, file.id);

    assert.equal(second!.content, first!.content, 'the same file produced different text');
    assert.equal(second!.chunkCount, first!.chunkCount);

    const extractionRows = await adminSql<{ n: number }[]>`
      select count(*)::int as n from drive_file_extractions where file_id = ${file.id}
    `;
    assert.equal(extractionRows[0]!.n, 1, 'a second extraction row was left behind');

    const chunkRows = await adminSql<{ c: number }[]>`
      select count(*)::int as c from drive_file_chunks where file_id = ${file.id}
    `;
    assert.equal(chunkRows[0]!.c, second!.chunkCount, 'orphaned chunks were left behind');
  });
});

describe('chunking is deterministic', () => {
  const document = Array.from({ length: 12 }, (_, i) =>
    `Section ${i + 1}${NL}${'This is a sentence about the brand and how it should sound. '.repeat(6)}`,
  ).join(NL + NL);

  it('produces identical chunks for identical text', () => {
    const a = chunker.chunkText(document);
    const b = chunker.chunkText(document);
    assert.deepEqual(a, b);
    assert.ok(a.length > 1, 'expected the document to split');
  });

  it('records offsets that point at the real source text', () => {
    for (const chunk of chunker.chunkText(document)) {
      assert.equal(chunk.content, document.slice(chunk.charStart, chunk.charEnd).trim());
      assert.ok(chunk.charEnd > chunk.charStart);
      assert.ok(chunk.tokenEstimate > 0);
    }
  });

  it('numbers chunks in order and overlaps them', () => {
    const chunks = chunker.chunkText(document);
    chunks.forEach((c, i) => assert.equal(c.ordinal, i));
    const overlapping = chunks.slice(1).filter((c, i) => c.charStart < chunks[i]!.charEnd);
    assert.ok(overlapping.length > 0, 'no chunk overlapped its predecessor');
  });

  it('returns nothing for empty text and one chunk for short text', () => {
    assert.deepEqual(chunker.chunkText(''), []);
    assert.deepEqual(chunker.chunkText('   ' + NL + '  '), []);
    assert.equal(chunker.chunkText('A short brand note.').length, 1);
  });

  it('splits a single huge paragraph rather than emitting it whole', () => {
    const wall = 'word '.repeat(2000);
    const chunks = chunker.chunkText(wall);
    assert.ok(chunks.length > 1);
    for (const c of chunks) assert.ok(c.content.length <= 1400, `chunk of ${c.content.length} chars`);
  });
});

describe('the queue is safe to share', () => {
  it('two workers claiming at once never take the same file', async () => {
    await parkPendingWork();
    const a = await upload(mm, 'race-a.txt', Buffer.from('First file for the race.'), 'text/plain');
    const b = await upload(mm, 'race-b.txt', Buffer.from('Second file for the race.'), 'text/plain');

    // Concurrent claims. FOR UPDATE SKIP LOCKED is what makes this safe: the
    // row one worker is taking is invisible to the other, not contended.
    const [first, second] = await Promise.all([processing.claimNextFile(), processing.claimNextFile()]);

    assert.ok(first && second, 'both claims should have found work');
    assert.notEqual(first.id, second.id, 'two workers claimed the same file');
    assert.deepEqual([first.id, second.id].sort(), [a.id, b.id].sort());

    for (const claimed of [first, second]) await processing.processClaimedFile(claimed);
    await drainQueue();
  });

  it('reclaims a file abandoned by a worker that died', async () => {
    await parkPendingWork();
    const file = await upload(mm, 'abandoned.txt', Buffer.from('Left mid-flight.'), 'text/plain');
    const claimed = await processing.claimNextFile();
    assert.equal(claimed?.id, file.id);

    // The worker vanishes: the row stays 'processing' with nothing working on it.
    await adminSql`
      update drive_files
         set processing_started_at = now() - (${processing.STUCK_AFTER_MINUTES + 5} * interval '1 minute')
       where id = ${file.id}
    `;
    assert.equal(await processing.claimNextFile(), null, 'a processing row must not be claimable');

    const reclaimed = await processing.recoverStuckFiles();
    assert.ok(reclaimed >= 1);

    const retry = await processing.claimNextFile();
    assert.equal(retry?.id, file.id, 'the abandoned file should be claimable again');
    await processing.processClaimedFile(retry!);
    assert.ok((await processing.getExtraction(mm, file.id))!.content.includes('Left mid-flight'));
  });

  it('reprocess puts a processed file back in the queue', async () => {
    const file = await upload(mm, 'again.txt', Buffer.from('Read me twice.'), 'text/plain');
    await drainQueue();

    await processing.requestReprocess(mm, file.id);
    const [row] = await adminSql<{ processing_status: string; processing_attempts: number; processed_at: Date | null }[]>`
      select processing_status, processing_attempts, processed_at from drive_files where id = ${file.id}
    `;
    assert.equal(row!.processing_status, 'pending');
    assert.equal(row!.processing_attempts, 0);
    assert.equal(row!.processed_at, null);
    await drainQueue();
  });

  it('the registry and the list the browser uses agree', () => {
    assert.deepEqual([...extraction.EXTRACTABLE_TYPES].sort(), ['csv', 'docx', 'pdf', 'txt']);
  });
});

describe('extractions and chunks stay inside their company', () => {
  let nhFileId: string;

  before(async () => {
    const file = await upload(nh, 'patient-consent-policy.txt',
      Buffer.from('Confidential Narayana policy about patient consent.'), 'text/plain');
    nhFileId = file.id;
    await drainQueue();
    assert.ok(await processing.getExtraction(nh, nhFileId), 'setup: the file should have been read');
  });

  it('company A cannot read company B extraction', async () => {
    await assert.rejects(() => processing.getExtraction(mm, nhFileId), /could not be found/i);
  });

  it('company A cannot reprocess company B file', async () => {
    await assert.rejects(() => processing.requestReprocess(mm, nhFileId), /could not be found/i);
  });

  it('an unfiltered query under A scope returns none of B rows', async () => {
    const rows = (await appSql.begin(async (tx) => {
      await tx`select set_config('cip.company_id', ${mm.companyId}, true)`;
      // deliberately no WHERE clause
      return tx<{ content: string }[]>`select content from drive_file_extractions`;
    })) as { content: string }[];

    assert.ok(rows.length > 0, 'expected Magic Moments to have extractions');
    assert.ok(!rows.some((r) => r.content.includes('Confidential Narayana')), 'an extraction leaked');

    const chunks = (await appSql.begin(async (tx) => {
      await tx`select set_config('cip.company_id', ${mm.companyId}, true)`;
      return tx<{ content: string }[]>`select content from drive_file_chunks`;
    })) as { content: string }[];
    assert.ok(!chunks.some((c) => c.content.includes('Confidential Narayana')), 'a chunk leaked');
  });

  it('with no company set, nothing is visible at all', async () => {
    assert.equal((await appSql`select id from drive_file_extractions`).length, 0);
    assert.equal((await appSql`select id from drive_file_chunks`).length, 0);
  });

  it('row-level security refuses an extraction written for another company', async () => {
    await assert.rejects(
      () => appSql.begin(async (tx) => {
        await tx`select set_config('cip.company_id', ${mm.companyId}, true)`;
        return tx`
          insert into drive_file_extractions (company_id, file_id, content, content_chars, extractor, extractor_version)
          values (${nh.companyId}, ${nhFileId}, 'planted', 7, 'x', '1')
        `;
      }),
      /row-level security/i,
    );
  });

  it('the composite key refuses a chunk whose extraction belongs elsewhere', async () => {
    const [ext] = await adminSql<{ id: string }[]>`
      select id from drive_file_extractions where file_id = ${nhFileId} limit 1
    `;
    // Even with row-level security bypassed entirely, referential integrity holds.
    await assert.rejects(
      () => adminSql`
        insert into drive_file_chunks (company_id, file_id, extraction_id, ordinal, content,
                                       char_start, char_end, token_estimate, chunker_version)
        values (${mm.companyId}, ${nhFileId}, ${ext!.id}, 0, 'crossed', 0, 7, 2, '1')
      `,
      /foreign key|violates/i,
    );
  });

  it('the worker writes every row under the file own company', async () => {
    const rows = await adminSql<{ file_company: string; extraction_company: string; chunk_company: string | null }[]>`
      select f.company_id as file_company,
             e.company_id as extraction_company,
             c.company_id as chunk_company
        from drive_files f
        join drive_file_extractions e on e.file_id = f.id
        left join drive_file_chunks c on c.extraction_id = e.id
    `;
    assert.ok(rows.length > 0);
    for (const row of rows) {
      assert.equal(row.extraction_company, row.file_company, 'an extraction landed in the wrong company');
      if (row.chunk_company) {
        assert.equal(row.chunk_company, row.file_company, 'a chunk landed in the wrong company');
      }
    }
  });
});
