/**
 * Radico Khaitan's creative QC rules, as written in their own QC document.
 *
 *   Radico_Khaitan_AI_Creative_QC_Master_Package_v1.1.md, Version 1.1, Oct 2026
 *
 * Version 1.1 gives every rule an asset scope - IMAGE, VIDEO or ALL - and
 * splits the logo standard: top-right on an image, centred on the end card of
 * a video. A brand's own logo rule keeps what holds for both (the approved
 * form, the colour); where the logo sits is the two global rules' job.
 *
 * WHY THESE ARE TYPED OUT AND NOT EXTRACTED BY A MODEL
 *
 * The document says it itself, in section 31: "DO NOT ALLOW THE MODEL TO INVENT
 * RULES". A model asked to read 1,800 lines of prose and emit a rule list will
 * produce a plausible one, and the rules it quietly invents are indistinguishable
 * from the rules it read. These are what the document says, transcribed, with
 * the section each came from recorded beside it - so any one of them can be
 * checked against the page it claims to come from in about ten seconds.
 *
 * WHAT IS DELIBERATELY NOT HERE
 *
 * Section 37 lists the products whose knowledge is not yet complete - the
 * individual Rampur variants, Kohinoor, Contessa, Morpheus, Jaisalmer, Burn
 * Barrel, Brown Barley, 8PM Premium Black, Virasat, Sangam, Ankahi - and says
 * plainly: "Do not fabricate product rules for these products." There are none
 * here for them.
 *
 * Section 10 and 11 describe 8PM's visual and copy preferences at length -
 * bold, premium, avoid cartoonish, avoid slang. Those are preferences, and the
 * document's own section 20 separates PREFERRED from MANDATORY: "Recommended,
 * but absence alone is not a violation." They are loaded as `preferred` with
 * `informational` severity, which is what stops them failing a creative.
 *
 * NOTHING HERE IS VERIFIED
 *
 * Every rule loads unverified. A person still has to confirm each one before it
 * can fail a creative outright, because a rule nobody has read is a rule nobody
 * has agreed to - and the document is a draft written by one team, not a signed
 * compliance position.
 */

export type RuleType =
  | 'mandatory'
  | 'prohibited'
  | 'preferred'
  | 'allowed'
  | 'conditional'
  | 'contextual'
  | 'human_review';

export type RuleSeverity = 'critical' | 'major' | 'minor' | 'informational';

export type QcRuleSeed = {
  /** The document's own identifier, or one built the same way where it gives none. */
  code: string;
  /** Which section of the document it was read from. */
  from: string;
  brand: string | null;
  product: string | null;
  market: string | null;
  domain: string;
  ruleType: RuleType;
  severity: RuleSeverity;
  rule: string;
  rationale: string | null;
  allowed: string[];
  prohibited: string[];
  humanReview: boolean;
  /** How CIP's older, two-valued column has to read this rule. */
  requirement: 'required' | 'forbidden';
  category: 'disclaimer' | 'audience' | 'claim' | 'placement' | 'medium' | 'other';
  /** Which creatives it is for. The document's "format"; every kind when it does not say. */
  format?: 'all' | 'image' | 'video';
};

const G = (
  n: string,
  fields: Omit<QcRuleSeed, 'code' | 'from' | 'brand' | 'product' | 'market'>,
): QcRuleSeed => ({
  code: `RADICO-GLOBAL-${n}`,
  from: `§5 RADICO-GLOBAL-${n}`,
  brand: null,
  product: null,
  market: null,
  ...fields,
});

/** A rule from §4.3, for video only. */
const V = (
  n: string,
  fields: Omit<QcRuleSeed, 'code' | 'from' | 'brand' | 'product' | 'market' | 'format'>,
): QcRuleSeed => ({
  code: `RADICO-VIDEO-${n}`,
  from: '§4.3 Video Analysis',
  brand: null,
  product: null,
  market: null,
  format: 'video',
  ...fields,
});

export const RADICO_QC_RULES: QcRuleSeed[] = [
  // ---- §5 Global rules -------------------------------------------------
  G('001', {
    domain: 'Language',
    ruleType: 'mandatory',
    severity: 'minor',
    rule: 'Use British English spelling. "Whisky", never "Whiskey".',
    rationale:
      'Radico communication uses British English. An official product name, registered asset, market requirement or supplied client artwork overrides this; flag only where there is a conflict.',
    allowed: ['Whisky'],
    prohibited: ['Whiskey'],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  }),
  G('002-IMG', {
    domain: 'Logo',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The brand logo should sit in the top-right corner.',
    rationale: 'Unless a documented campaign or format exception exists. A viewer sees an image all at once; the logo sits in a corner, visible without covering the message. v1.1: never applied to video.',
    allowed: [],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'placement',
    format: 'image',
  }),
  G('002-VID', {
    domain: 'Logo',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The brand logo must appear centred on the end card (last frame). It is not required during the video, and a small corner logo or watermark during the video is acceptable.',
    rationale: 'v1.1: the brand signs off on the end card, the moment the viewer remembers. A logo shown mid-video but not on the end card, or on the end card but not centred, breaks it. Never applied to images.',
    allowed: ['No logo during the video', 'Small corner logo or watermark during the video'],
    prohibited: ['No logo on the end card', 'End card logo not centred'],
    humanReview: true,
    requirement: 'required',
    category: 'placement',
    format: 'video',
  }),
  G('003', {
    domain: 'Logo',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not alter, distort, recolour, stretch, rotate or otherwise modify an approved brand logo.',
    rationale: null,
    allowed: [],
    prohibited: ['Distorted logo', 'Recoloured logo', 'Stretched logo', 'Rotated logo'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
  }),
  G('004', {
    domain: 'Pack / Product',
    ruleType: 'contextual',
    severity: 'major',
    rule: 'Where the creative is meant to communicate the product, the approved pack should be visible.',
    rationale: 'Unless the campaign brief explicitly permits a pack-free execution.',
    allowed: [],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  }),
  G('005', {
    domain: 'Pack / Product',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Product packaging must not be distorted or incorrectly generated.',
    rationale:
      'Covers incorrect bottle proportions, label, logo, cap, bottle colour, liquid colour, AI-generated packaging errors, and missing or malformed packaging elements.',
    allowed: [],
    prohibited: [
      'Incorrect bottle proportions',
      'Incorrect label',
      'Incorrect cap',
      'Incorrect bottle colour',
      'Incorrect liquid colour',
      'AI-generated packaging errors',
      'Malformed packaging elements',
    ],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
  }),
  G('006', {
    domain: 'Competitor',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Competitor brand logos must not appear.',
    rationale: 'Unless explicitly required by an approved campaign or legal context.',
    allowed: [],
    prohibited: ['Competitor logos'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
  }),
  G('007', {
    domain: 'Competitor',
    ruleType: 'human_review',
    severity: 'major',
    rule: 'Flag obvious competitor packaging or branding that could create confusion.',
    rationale:
      'Do not flag generic shapes merely because they resemble another product. A bottle looking like a bottle is not an imitation.',
    allowed: ['Generic bottle shapes'],
    prohibited: [],
    humanReview: true,
    requirement: 'forbidden',
    category: 'other',
  }),
  G('008', {
    domain: 'Alcohol Compliance',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not depict underage people consuming or taking part in alcohol consumption.',
    rationale:
      'Includes obviously school- or college-looking, or otherwise underage-coded, representation in drinking contexts.',
    allowed: [],
    prohibited: ['Underage people', 'School or college-looking people in drinking contexts'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'audience',
  }),
  G('009', {
    domain: 'Alcohol Compliance',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not depict or imply drinking and driving.',
    rationale: null,
    allowed: [],
    prohibited: ['Driving after drinking', 'Car keys with alcohol', 'Driving environments'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'claim',
  }),
  G('010', {
    domain: 'Alcohol Compliance',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not show intoxication, excessive drinking, drinking contests or games, or encourage heavy consumption.',
    rationale: null,
    allowed: [],
    prohibited: ['Intoxication', 'Drunk behaviour', 'Drinking contests', 'Drinking games'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'claim',
  }),
  G('011', {
    domain: 'Alcohol Compliance',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not present alcohol as providing health or medical benefits.',
    rationale: null,
    allowed: [],
    prohibited: ['Health claims', 'Medical benefit claims'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'claim',
  }),
  G('012', {
    domain: 'Alcohol Compliance',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not imply that drinking causes professional success, financial success, social status or improved performance.',
    rationale: 'Unless specifically approved through applicable legal or client guidance.',
    allowed: [],
    prohibited: ['Professional success claims', 'Financial success claims', 'Social status claims'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'claim',
  }),
  G('013', {
    domain: 'Cultural',
    ruleType: 'human_review',
    severity: 'major',
    rule: 'Flag politically, religiously or culturally sensitive references for a person to look at.',
    rationale:
      'Political references, religious symbolism, figures or places, national symbols and sensitive social issues, unless explicitly approved for the campaign.',
    allowed: [],
    prohibited: [],
    humanReview: true,
    requirement: 'forbidden',
    category: 'other',
  }),

  // ---- Said by the Radico team, 10 Oct 2026 ------------------------------
  // Not in the document. "Use the chocolate flavour bottle" came back covered
  // in chocolate; the flavour is the pack, not a prop.
  {
    code: 'RADICO-GEN-FLAV-001',
    from: 'Radico team instruction, 10 Oct 2026',
    brand: null,
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'preferred',
    severity: 'minor',
    rule:
      'A flavour named in the request - Chocolate, Honey, Fire - is the variant whose approved pack is shown. ' +
      'Do not add the flavour itself (chocolate, honey, bees, cinnamon, fruit) to the picture unless the request asks for it.',
    rationale:
      'The pack and its name already say the flavour. Ingredient imagery added on its own reads as a different product.',
    allowed: ['The flavour variant\'s approved pack', 'Flavour imagery when the request asks for it'],
    prohibited: ['Chocolate, honey or other flavour ingredients added without being asked for'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
    format: 'all',
  },

  // ---- §8 8PM Honey ----------------------------------------------------
  {
    code: '8PM_HONEY_VIS_001',
    from: '§8 HARD PROHIBITION',
    brand: '8PM',
    product: '8PM Honey',
    market: null,
    domain: 'Visual',
    ruleType: 'prohibited',
    severity: 'major',
    rule: 'Bee imagery must not be used on 8PM Honey.',
    rationale:
      'Honey is an approved flavour territory; bees specifically are not. The prohibition does not extend to honey itself.',
    allowed: ['Honey', 'Honeycomb', 'Honey textures', 'Golden tones', 'Warm lighting', 'Golden sunset', 'Sweetness metaphors'],
    prohibited: ['Bees', 'Bee imagery', 'Bee characters', 'Bee illustrations'],
    humanReview: true,
    requirement: 'forbidden',
    category: 'other',
  },
  {
    code: '8PM_HONEY_FLAV_001',
    from: '§8 Preferred Communication',
    brand: '8PM',
    product: '8PM Honey',
    market: null,
    domain: 'Flavour',
    ruleType: 'preferred',
    severity: 'informational',
    rule: 'The honey flavour profile should be promoted or explained, literally or metaphorically.',
    rationale: null,
    allowed: [],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },

  // ---- §9 8PM Fire -----------------------------------------------------
  {
    code: '8PM_FIRE_FLAV_001',
    from: '§9 Visual Territory',
    brand: '8PM',
    product: '8PM Fire',
    market: null,
    domain: 'Flavour',
    ruleType: 'allowed',
    severity: 'informational',
    rule: 'Heat, fire, warmth and cinnamon cues are approved territory for 8PM Fire.',
    rationale:
      'The flavour is cinnamon-derived with a fiery finish. Do not invent ingredient or flavour claims beyond that.',
    allowed: ['Heat', 'Fire', 'Warmth', 'Cinnamon cues', 'Fiery metaphors'],
    prohibited: ['Unsupported ingredient claims', 'Unsupported flavour claims'],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },

  // ---- §10, §11 8PM visual and copy system -----------------------------
  {
    code: '8PM_VIS_001',
    from: '§10 Avoid',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'preferred',
    severity: 'minor',
    rule: '8PM should look bold, premium and cinematic — not teen-oriented, cartoonish, cheap or corporate.',
    rationale: 'A preference, not a requirement: absence alone is not a violation.',
    allowed: ['Bold', 'Premium', 'Strong typography', 'Cinematic', 'Lifestyle', 'Urban'],
    prohibited: ['Teen-oriented', 'Cartoonish', 'Cheap or generic', 'Extremely corporate'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },
  {
    code: '8PM_PEOPLE_001',
    from: '§10 Styling',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'People',
    ruleType: 'prohibited',
    severity: 'critical',
    rule: 'Do not show school- or college-looking, or obviously underage-looking, people.',
    rationale: null,
    allowed: ['Young adults', 'Working professionals', 'Friends and groups', 'Couples'],
    prohibited: ['School or college-looking people', 'Underage-looking people', 'Excessively provocative clothing'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'audience',
  },
  {
    code: '8PM_ENV_001',
    from: '§10 Locations',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Environment',
    ruleType: 'prohibited',
    severity: 'major',
    rule: 'Avoid religious places, hospitals, schools, places associated with children, workplaces, gyms and driving environments.',
    rationale: null,
    allowed: ['Home', 'Bar or lounge', 'Restaurant', 'Urban cityscape'],
    prohibited: ['Religious places', 'Hospitals', 'Schools', 'Places associated with children', 'Workplaces', 'Gyms', 'Driving environments'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
  },
  {
    code: '8PM_COPY_001',
    from: '§11 Avoid / Slang',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Copy',
    ruleType: 'preferred',
    severity: 'minor',
    rule: '8PM copy should read bold, confident and premium — avoid slang, generic motivational lines and overly poetic or corporate writing.',
    rationale: 'A preference, not a requirement.',
    allowed: ['Bold', 'Confident', 'Aspirational', 'Witty'],
    prohibited: ['Slang', 'Generic motivational copy', 'Overly poetic copy', 'Corporate copy'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §14 Whytehall ---------------------------------------------------
  {
    code: 'WHYTEHALL_LOGO_001',
    from: '§14 WHYTEHALL LOGO',
    brand: 'Whytehall',
    product: null,
    market: null,
    domain: 'Logo',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The Whytehall logo must stay as approved and keep its colour.',
    rationale: null,
    allowed: [],
    prohibited: ['Recoloured logo'],
    humanReview: false,
    requirement: 'required',
    category: 'placement',
  },
  {
    code: 'WHYTEHALL_HONEY_001',
    from: '§13 Honey',
    brand: 'Whytehall',
    product: 'Whytehall Honey',
    market: null,
    domain: 'Visual',
    ruleType: 'allowed',
    severity: 'informational',
    rule: "8PM Honey's bee prohibition does not apply to Whytehall Honey.",
    rationale:
      'Stated explicitly in the document so the rule is not carried across by resemblance. Add a Whytehall-specific rule if one is ever wanted.',
    allowed: ['Honey', 'Sweetness'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'WHYTEHALL_TONE_001',
    from: '§12 Key Difference from 8PM',
    brand: 'Whytehall',
    product: null,
    market: null,
    domain: 'Brand Identity',
    ruleType: 'preferred',
    severity: 'minor',
    rule: 'Whytehall should feel like a well-organised, refined celebration rather than a loud party.',
    rationale: '8PM can own the stronger party vibe; Whytehall is the refined one.',
    allowed: ['Refined', 'Organised', 'Sophisticated', 'Elevated'],
    prohibited: ['Loud party treatment'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §15 AfriBull ----------------------------------------------------
  {
    code: 'AFRIBULL_POS_001',
    from: '§15 Positioning / Avoid',
    brand: 'Afri Bull',
    product: null,
    market: null,
    domain: 'Brand Identity',
    ruleType: 'preferred',
    severity: 'minor',
    rule: 'AfriBull must not look cheap, and must not be dressed up as ultra-luxury either.',
    rationale: 'Both directions are wrong for this product.',
    allowed: ['Café flavour notes', 'African heritage', 'African culture', 'Heritage storytelling'],
    prohibited: ['Cheap-looking execution', 'Generic low-cost visual language', 'Artificial luxury positioning'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'AFRIBULL_LOGO_001',
    from: '§15 Branding',
    brand: 'Afri Bull',
    product: null,
    market: null,
    domain: 'Logo',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The AfriBull logo stays consistent, and the rum colour stays accurate.',
    rationale: null,
    allowed: [],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'placement',
  },

  // ---- §16 Magic Moments -----------------------------------------------
  {
    code: 'MM_LOGO_001',
    from: '§16 Logo',
    brand: 'Magic Moments',
    product: null,
    market: null,
    domain: 'Logo',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The Magic Moments logo is blue or white, and must not be recoloured outside those two.',
    rationale: 'Both blue and white are approved. Neither is more correct than the other.',
    allowed: ['Blue logo', 'White logo'],
    prohibited: ['Any other logo colour'],
    humanReview: false,
    requirement: 'required',
    category: 'placement',
  },
  {
    code: 'MM_COPY_001',
    from: '§16 Brand Copy Territory',
    brand: 'Magic Moments',
    product: null,
    market: null,
    domain: 'Copy',
    ruleType: 'preferred',
    severity: 'informational',
    rule: '"Magic Moments" is worth working into the copy, but its absence is not a failure.',
    rationale:
      'The document says so directly: unless a campaign makes it mandatory, absence should not be treated as a compliance failure.',
    allowed: ['Magic Moments', 'Flavor of Your Life', 'Make Every Moment a Magic Moment'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'MM_POS_001',
    from: '§16 Positioning',
    brand: 'Magic Moments',
    product: null,
    market: null,
    domain: 'Brand Identity',
    ruleType: 'preferred',
    severity: 'minor',
    rule: 'Magic Moments is fun, social and contemporary — not an ultra-luxury product.',
    rationale: 'It is widely consumed and should not be treated as ultra-luxury.',
    allowed: ['Fun', 'Party', 'Social', 'Contemporary'],
    prohibited: ['Ultra-luxury treatment'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §17 Rampur ------------------------------------------------------
  {
    code: 'RAMPUR_LOGO_001',
    from: '§17 Logo System',
    brand: 'Rampur',
    product: null,
    market: null,
    domain: 'Logo',
    ruleType: 'human_review',
    severity: 'major',
    rule: 'Two Rampur logo identities are both valid — "Rampur Distillery" and "Rampur Indian Single Malt Whisky". Do not treat either as the only correct one.',
    rationale:
      'Which is right depends on the client, campaign and product. Placement follows the Radico standard: top-right on an image, centred on the end card of a video.',
    allowed: ['Rampur Distillery logo', 'Rampur Indian Single Malt Whisky logo'],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'placement',
  },
  {
    code: 'RAMPUR_LUX_001',
    from: '§17 Creative Territory',
    brand: 'Rampur',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'preferred',
    severity: 'minor',
    rule: 'Luxury must come from the whole execution — copy, composition, light, props, typography — not one visual cue.',
    rationale: 'Avoid mass-market, cheap, casual or loud treatment where it conflicts with the product.',
    allowed: [],
    prohibited: ['Mass-market treatment', 'Cheap treatment', 'Excessively loud treatment'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §18 Blue Finest, market terminology ------------------------------
  {
    code: 'BLUE_FINEST_MARKET_001',
    from: '§18 Thailand',
    brand: 'Blue Finest',
    product: null,
    market: 'Thailand',
    domain: 'Market',
    ruleType: 'conditional',
    severity: 'major',
    rule: 'In Thailand the product is "Blue Finest Whisky Spirit".',
    rationale: 'Terminology is judged against the target market. Neither wording is correct everywhere.',
    allowed: ['Blue Finest Whisky Spirit'],
    prohibited: ['Blue Finest Whisky'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'BLUE_FINEST_MARKET_002',
    from: '§18 Africa / Rest of Africa',
    brand: 'Blue Finest',
    product: null,
    market: null,
    domain: 'Market',
    ruleType: 'conditional',
    severity: 'major',
    rule: 'In Africa the product is "Blue Finest Whisky".',
    rationale:
      'Loaded without a market because CIP holds African markets under their own names. Confirm the market before this one is trusted to fail anything.',
    allowed: ['Blue Finest Whisky'],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §19 Royal Ranthambore --------------------------------------------
  {
    code: 'RR_VIS_001',
    from: '§19 Tiger Rule',
    brand: 'Royal Ranthambore',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'allowed',
    severity: 'informational',
    rule: 'Tiger imagery is an approved association for Royal Ranthambore. Do not flag it as stray wildlife.',
    rationale:
      'Ranthambore is strongly associated with tigers, royalty and Indian heritage. The tiger is the point, not an error.',
    allowed: ['Tiger', 'Royal imagery', 'Rajasthan cues', 'Indian heritage'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'RR_VIS_002',
    from: '§19 Tiger Rule',
    brand: 'Royal Ranthambore',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'human_review',
    severity: 'minor',
    rule: 'Flag cheap, gimmicky or cartoonish tiger treatment that weakens the premium positioning.',
    rationale: 'The distinction is subjective, so it goes to a person rather than being decided outright.',
    allowed: ['Sophisticated tiger representation'],
    prohibited: ['Cartoonish tiger', 'Gimmicky tiger treatment', 'Generic wildlife treatment'],
    humanReview: true,
    requirement: 'forbidden',
    category: 'other',
  },
  {
    code: 'RR_COPY_001',
    from: '§19 Tagline',
    brand: 'Royal Ranthambore',
    product: null,
    market: null,
    domain: 'Copy',
    ruleType: 'preferred',
    severity: 'informational',
    rule: '"India’s Finest Yet" is the established tagline, but it is not required in every execution.',
    rationale: 'Only force it where the campaign brief requires it.',
    allowed: ['India’s Finest Yet'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'RR_LOGO_001',
    from: '§19 Logo',
    brand: 'Royal Ranthambore',
    product: null,
    market: null,
    domain: 'Logo',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The Royal Ranthambore logo keeps its approved form.',
    rationale: null,
    allowed: [],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'placement',
  },

  // ---- §7, §10 the rest of 8PM -----------------------------------------
  {
    code: '8PM_TONE_001',
    from: '§7 Brand Personality',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Brand Identity',
    ruleType: 'preferred',
    severity: 'minor',
    rule: "8PM's masculinity is charisma and confidence, not aggression.",
    rationale: 'The document says so in as many words, because the two are easy to confuse in a brief.',
    allowed: ['Bold', 'Sophisticated', 'Confident', 'Aspirational', 'Charisma'],
    prohibited: ['Aggression'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },
  {
    code: '8PM_COPY_002',
    from: '§7 Brand Communication Associations',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Copy',
    ruleType: 'allowed',
    severity: 'informational',
    rule: '"Time of Your Life" and "Time for Friends" are 8PM associations, not required copy.',
    rationale:
      'Reference language rather than mandatory, unless campaign guidance says otherwise. Absence is not a fault.',
    allowed: ['Time of Your Life', 'Time for Friends'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },
  {
    code: '8PM_COLOUR_001',
    from: '§10 Colour',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'Approved 8PM brand colours must be preserved, and should dominate where applicable.',
    rationale: null,
    allowed: [],
    prohibited: ['Altered brand colours'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },
  {
    code: '8PM_PROPS_001',
    from: '§10 Props',
    brand: '8PM',
    product: null,
    market: null,
    domain: 'Props',
    ruleType: 'allowed',
    severity: 'informational',
    rule: 'Whisky glasses, ice, food, cigars, music props and lifestyle objects are approved for 8PM.',
    rationale:
      'Recorded so an approved prop is not flagged as a stray object. Permission, not a requirement.',
    allowed: ['Whisky glasses', 'Ice', 'Food', 'Cigars', 'Music-related props', 'Lifestyle objects'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },

  // ---- §13 Whytehall flavours ------------------------------------------
  {
    code: 'WHYTEHALL_FLAV_001',
    from: '§13 Flavour Communication',
    brand: 'Whytehall',
    product: null,
    market: null,
    domain: 'Flavour',
    ruleType: 'preferred',
    severity: 'informational',
    rule: 'Whytehall Chocolate and Honey should communicate their flavour, literally or metaphorically.',
    rationale: 'Fire is cinnamon-derived. Do not claim ingredients beyond that.',
    allowed: ['Chocolate cues', 'Honey cues', 'Cinnamon cues', 'Metaphorical flavour'],
    prohibited: ['Unsupported ingredient claims'],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },

  // ---- §15 the rest of AfriBull ----------------------------------------
  {
    code: 'AFRIBULL_CULT_001',
    from: '§15 Visual Freedom',
    brand: 'Afri Bull',
    product: null,
    market: null,
    domain: 'Cultural',
    ruleType: 'human_review',
    severity: 'major',
    rule: 'African cultural representation must be authentic and respectful — send it to a person.',
    rationale:
      'Broad creative freedom is allowed around African heritage. Whether an execution is respectful is not a judgement to leave to a machine.',
    allowed: ['African cultural elements', 'Heritage storytelling'],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'AFRIBULL_TERR_001',
    from: '§15 Core Territory',
    brand: 'Afri Bull',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'allowed',
    severity: 'informational',
    rule: 'Café and coffee notes, African heritage and culture are approved AfriBull territory.',
    rationale: 'Recorded so they read as on-brand rather than as stray content.',
    allowed: ['Café flavour notes', 'Coffee elements', 'African heritage', 'African culture', 'Sensory metaphors'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },

  // ---- §16 Magic Moments flavours --------------------------------------
  {
    code: 'MM_FLAV_001',
    from: '§16 Product Communication',
    brand: 'Magic Moments',
    product: null,
    market: null,
    domain: 'Flavour',
    ruleType: 'allowed',
    severity: 'informational',
    rule: 'Flavour is a major Magic Moments territory — literal or metaphorical representation is allowed.',
    rationale:
      'The portfolio is Plain Grain, Raspberry, Green Apple, Lemongrass & Ginger, Orange, Chocolate and Spicy Jamun Mint.',
    allowed: [
      'Raspberry', 'Green Apple', 'Lemongrass & Ginger', 'Orange', 'Chocolate',
      'Spicy Jamun Mint', 'Plain Grain', 'Metaphorical flavour',
    ],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },

  // ---- §17, §37 the guard the document asks for -------------------------
  {
    code: 'RAMPUR_VAR_001',
    from: '§17 Important / §37',
    brand: 'Rampur',
    product: null,
    market: null,
    domain: 'Brand Identity',
    ruleType: 'human_review',
    severity: 'minor',
    rule: 'Do not make specific claims about an individual Rampur variant — send it to a person.',
    rationale:
      'The document says product rules must be added before the system makes highly specific claims about individual Rampur variants. None have been.',
    allowed: [],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §19 the rest of Royal Ranthambore --------------------------------
  {
    code: 'RR_TERR_001',
    from: '§19 Core Brand Territory',
    brand: 'Royal Ranthambore',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'allowed',
    severity: 'informational',
    rule: 'Royalty, Ranthambore, Rajasthan and Indian royal heritage are approved territory.',
    rationale: 'Recorded so heritage cues read as on-brand rather than as stray content.',
    allowed: ['Royalty', 'Ranthambore', 'Rajasthan', 'Indian royal heritage', 'Majestic character'],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  },
  {
    code: 'RR_VIS_003',
    from: '§19 Visual Direction',
    brand: 'Royal Ranthambore',
    product: null,
    market: null,
    domain: 'Visual',
    ruleType: 'preferred',
    severity: 'minor',
    rule: 'Royal Ranthambore should read royal, majestic, premium and refined.',
    rationale: 'A preference. Absence alone is not a violation.',
    allowed: ['Royal', 'Majestic', 'Premium', 'Refined', 'Rajasthan-inspired'],
    prohibited: [],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  },

  // ---- §4.3 Video Analysis ------------------------------------------------
  //
  // Section 4.3 lists what is evaluated on a video and on nothing else. It is
  // a list of things to look at, not a list of rules: it gives no type and no
  // severity. Each one below is that item, worded as something a film can be
  // checked against, with the type and severity CIP's reading - kept low, and
  // `human_review` wherever the document gives nothing to judge by, so that a
  // rule the document did not quite write cannot fail a film on its own.
  //
  // Everything else in the document - the logo, the pack, competitors,
  // drinking and driving, claims, British English - applies to a video as it
  // does to a picture, and is already above with format "all".
  V('001', {
    domain: 'Pack / Product',
    ruleType: 'prohibited',
    severity: 'major',
    rule: 'The pack must stay the same approved pack in every shot - no shot where the bottle, label, cap or liquid changes, warps or is generated wrongly.',
    rationale: '§4.3 lists pack integrity and continuity. §5 RADICO-GLOBAL-005 is the rule; on a film it has to hold in every shot, and a pack that is right on the end card and wrong mid-film breaks it.',
    allowed: [],
    prohibited: ['A pack that changes between shots', 'Warped or melting bottle mid-shot', 'Label that is wrong in some shots'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
  }),
  V('002', {
    domain: 'VO',
    ruleType: 'prohibited',
    severity: 'major',
    rule: 'The voiceover is held to the same claim rules as the on-screen copy: no spoken health benefit, success claim or encouragement to drink to excess.',
    rationale: '§4.3 lists the VO. §5 RADICO-GLOBAL-010, -011 and -012 forbid these claims in Radico communication, which a spoken line is as much as a written one.',
    allowed: [],
    prohibited: ['Spoken health or medical benefit', 'Spoken professional, financial or social success from drinking', 'Spoken encouragement to drink more'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'claim',
  }),
  V('003', {
    domain: 'Subtitles',
    ruleType: 'mandatory',
    severity: 'minor',
    rule: 'Subtitles, where there are any, must say what the voiceover says.',
    rationale: '§4.3 lists subtitles alongside the VO.',
    allowed: [],
    prohibited: ['Subtitles that differ from the voiceover'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  }),
  V('004', {
    domain: 'Language',
    ruleType: 'mandatory',
    severity: 'minor',
    rule: 'On-screen text and subtitles must be spelt correctly, with the product named exactly as it is officially written.',
    rationale: '§4.3 lists spelling and product terminology. §5 RADICO-GLOBAL-001 sets British English.',
    allowed: [],
    prohibited: ['Misspelt on-screen text', 'Misspelt or wrong product name'],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  }),
  V('005', {
    domain: 'Legal / Compliance',
    ruleType: 'human_review',
    severity: 'major',
    rule: 'Disclaimers and statutory lines must be on screen long enough to be read, not flashed.',
    rationale: '§4.3 lists the disclaimer and timing. The document gives no minimum duration, so a person judges what is long enough.',
    allowed: [],
    prohibited: ['A disclaimer shown too briefly to read'],
    humanReview: true,
    requirement: 'required',
    category: 'disclaimer',
  }),
  V('006', {
    domain: 'Brand Identity',
    ruleType: 'mandatory',
    severity: 'major',
    rule: 'The end screen must show the approved logo and the approved pack, legibly.',
    rationale: '§4.3 lists the end screen, logo and pack visibility. On a film, the end screen is where the brand is signed off.',
    allowed: [],
    prohibited: ['An end screen without the logo', 'An end screen with an unapproved or distorted pack'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  }),
  V('007', {
    domain: 'AI Artefact',
    ruleType: 'prohibited',
    severity: 'major',
    rule: 'No AI artefacts in any frame: warped hands or faces, melting objects, garbled text, or things that appear and vanish between frames.',
    rationale: '§4.3 lists AI artefacts. §4.1 names distortion, unnatural anatomy and product manipulation.',
    allowed: [],
    prohibited: ['Warped hands or faces', 'Melting or morphing objects', 'Garbled text', 'Objects popping in and out'],
    humanReview: false,
    requirement: 'forbidden',
    category: 'other',
  }),
  V('008', {
    domain: 'Animation',
    ruleType: 'prohibited',
    severity: 'minor',
    rule: 'Transitions and animation must not break the logo, the pack or the text mid-movement - no tearing, glitches or half-drawn frames.',
    rationale: '§4.3 lists transitions and animation. §5 RADICO-GLOBAL-003 forbids altering the logo, which a glitch in a transition does.',
    allowed: [],
    prohibited: ['Logo torn or glitched in a transition', 'Pack half-rendered mid-animation'],
    humanReview: true,
    requirement: 'forbidden',
    category: 'other',
  }),
  V('009', {
    domain: 'Visual',
    ruleType: 'prohibited',
    severity: 'minor',
    rule: 'Colour grading must keep the pack, label and liquid their true colours.',
    rationale: '§4.3 lists colour grading. §5 RADICO-GLOBAL-005 flags an incorrect bottle or liquid colour.',
    allowed: [],
    prohibited: ['A grade that changes the bottle, label or liquid colour'],
    humanReview: true,
    requirement: 'forbidden',
    category: 'other',
  }),
  V('010', {
    domain: 'Audio',
    ruleType: 'human_review',
    severity: 'minor',
    rule: 'Song lyrics must not say what the copy may not: drinking to excess, drinking and driving, or health and success claims.',
    rationale: '§4.3 lists the music. A lyric heard over the film is part of what it says; lyrics are often misheard, so a person decides.',
    allowed: [],
    prohibited: ['Lyrics about drinking to excess', 'Lyrics about drinking and driving'],
    humanReview: true,
    requirement: 'forbidden',
    category: 'claim',
  }),
  V('011', {
    domain: 'CTA',
    ruleType: 'preferred',
    severity: 'informational',
    rule: 'Any call to action should be legible and on screen long enough to read.',
    rationale: '§4.3 lists the CTA and timing. A preference: absence of a CTA is not a violation.',
    allowed: [],
    prohibited: [],
    humanReview: false,
    requirement: 'required',
    category: 'other',
  }),
  V('012', {
    domain: 'Technical',
    ruleType: 'human_review',
    severity: 'minor',
    rule: "The film's aspect ratio and resolution must suit where it runs, with nothing important cut off at the edges.",
    rationale: '§4.3 lists aspect ratio and resolution; §26 Step 1 records them. Which is right depends on the placement, which a person knows.',
    allowed: [],
    prohibited: ['Logo, pack or disclaimer cut off at the frame edge'],
    humanReview: true,
    requirement: 'required',
    category: 'other',
  }),
];
