import { noStore, withMediaScope } from '@/server/media/http';
import { readAsset } from '@/server/media/generation';

/**
 * GET /api/media/generations/[id]/asset
 *
 * The generated bytes, served by the application after it has proved the
 * session — the same arrangement the Drive uses. There is no signed URL to
 * leak and no public object to misconfigure, and the storage path never
 * appears in a response.
 *
 * ?assetId= picks one file from a generation that produced several. An asset
 * id from another company does not resolve, because the lookup is joined
 * through this company's own generation.
 */
export const dynamic = 'force-dynamic';

export async function GET(request: Request, context: { params: Promise<{ id: string }> }) {
  const { id } = await context.params;
  const assetId = new URL(request.url).searchParams.get('assetId');

  return withMediaScope(async (scope) => {
    const asset = await readAsset(scope, id, assetId);

    return new Response(new Uint8Array(asset.bytes), {
      headers: {
        ...noStore,
        'content-type': asset.mimeType,
        'content-length': String(asset.fileSize),
        // inline, not attachment: these are meant to be looked at.
        'content-disposition': 'inline',
        'x-content-type-options': 'nosniff',
      },
    });
  });
}
